version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html


  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
