version: '2'

volumes:
  rabbitmq:
  redis:

services:
  rabbit:
    image: rabbitmq:3
    restart: always
    environment:
      RABBITMQ_NODENAME: node@rabbit
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia

  redis:
    image: redis:4
    restart: always
    command: [redis-server, --appendonly, 'yes']
    volumes:
      - redis:/data

  bridge:
    image: thundercore/bridge
    build: ../../validator
    environment:
      - NODE_ENV=production
    env_file: ./.env
    logging:
      driver: json-file
      options:
        max-size: '5m'
        max-file: '10'

  bridge_request:
    extends: bridge
    restart: always
    command: npm run watcher:signature-request
    depends_on:
      - rabbit
      - redis

  bridge_collected:
    extends: bridge
    restart: always
    command: npm run watcher:collected-signatures
    depends_on:
      - rabbit
      - redis

  bridge_affirmation:
    extends: bridge
    restart: always
    command: npm run watcher:affirmation-request
    depends_on:
      - rabbit
      - redis

  bridge_home:
    extends: bridge
    restart: always
    command: npm run sender:home
    depends_on:
      - rabbit
      - redis

  bridge_foreign:
    extends: bridge
    restart: always
    command: npm run sender:foreign
    depends_on:
      - rabbit
      - redis

  receiptor_home:
    extends: bridge
    restart: always
    command: npm run receiptor:home
    depends_on:
      - rabbit
      - redis

  receiptor_foreign:
    extends: bridge
    restart: always
    command: npm run receiptor:foreign
    depends_on:
      - rabbit
      - redis