FROM node:10

RUN mkdir /contracts
WORKDIR /contracts

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .
RUN rm -r migrations

RUN npm run compile && ./flatten.sh

CMD [ "npm", "test" ]