export { ReactComponent as TutorialIcon } from './ic_tutorial.svg'
export * from './EventsIcon'
export * from './MobileMenuCloseIcon'
export * from './MobileMenuIcon'
export * from './StatisticsIcon'
export * from './StatusIcon'
