version: '2'

volumes:
  statics:

services:
  ui:
    image: thundercore/bridge-ui
    build: ../../ui
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    environment:
      VIRTUAL_HOST: $UI_HOSTNAME
      LETSENCRYPT_HOST: $UI_HOSTNAME
    env_file: ./.env
    volumes:
      - statics:/statics

networks:
  default:
    external:
      name: frontend_default