version: '2'

volumes:
  statics:

services:
  ui:
    image: thundercore/bridge-ui
    build: ../../ui
    environment:
      VIRTUAL_HOST: $UI_HOSTNAME
      LETSENCRYPT_HOST: $UI_HOSTNAME
    env_file: ./.env
    volumes:
      - statics:/statics

networks:
  default:
    external:
      name: frontend_default