version: '2'
volumes:
  home_data:
  foreign_data:
  redis_data:
  rabbit_data:

services:
  home-chain:
    build: thunder
    restart: always
    volumes:
      - home_data:/thunder/pala-dev/dataDir/single
    ports:
      - "8540:8546"
      - "8541:8545"
  foreign-chain:
    build: thunder
    restart: always
    volumes:
      - foreign_data:/thunder/pala-dev/dataDir/single
    ports:
      - "8542:8545"
  redis:
    image: "redis:4"
    restart: always
    volumes:
      - redis_data:/data
    ports:
     - "6379:6379"
  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672"